- hosts: ansible-server

  tasks:
  - name: p4 sync
    shell: p4 sync //splunk/current/test/data/...
    environment: P4ENV

  - name: copy directory from local to remote
    local_action: command rsync -a /home/eserv/perforce/splunk/current $inventory_host:/home/eserv/perforce/splunk

- hosts: ansible-client-peer1

  tasks:
  - name: stop splunk
    command: ${splunk_cmd} stop removes=${splunk_cmd}
    ignore_errors: true

  - name: delete splunk_home_peer1
    file: path=${splunk_home_peer1} state=absent

  - name: get splunk pkg
    get_url: dest=/tmp/splunk.tgz force=yes url=${splunk_pkg_url}

  - name: extract splunk pkg
    command: tar xzf /tmp/splunk.tgz chdir=${splunk_home_peer1_parent} creates=${splunk_cmd_peer1}

  - name: chmod 0644 ${server_conf}
    file: path=${server_conf} mode=0644

  - name: enable admin login in ${server_conf}
    lineinfile: dest=${server_conf} regexp='allowRemoteLogin=' line='allowRemoteLogin = always' state=present

  - name: disable splunkweb in ${web_conf}
    lineinfile: dest=${web_conf} regexp='startwebserver\s=' line='startwebserver = 0' state=present

  - name: change default splunkd-port in ${web_conf}
    lineinfile: dest=${web_conf} regexp='mgmtHostPort\s=' line='mgmtHostPort = 127.0.0.1:9998' state=present

  - name: chmod 0644 ${props_conf}
    file: path=${props_conf} mode=0644

  - name: set DATETIME_CONFIG = CURRENT in ${props_conf}
    lineinfile: dest=${props_conf} regexp='DATETIME_CONFIG\s=\s/etc/datetime.xml' line='DATETIME_CONFIG = CURRENT' state=present

  - name: start splunk
    command: ${splunk_cmd_peer1} start --accept-license --answer-yes --auto-ports removes=${splunk_cmd_peer1}
    register: start_splunk_output

  - name: display splunk start output
    shell: echo ${start_splunk_output}
    when: start_splunk_output

  - name: save splunkd-port
    shell: ${splunk_cmd_peer1} show splunkd-port -auth admin:changeme >> ./splunkd-port.txt creates=${splunk_cmd_peer1}

  - name: stdout splunkd-port
    shell: ${splunk_cmd_peer1} show splunkd-port -auth admin:changeme
    register: splunkd_port

  - shell: echo "splunk show splunkd-port works"
    when: splunkd_port.stdout.find('9998') != -1


- hosts: ansible-client-sh1

  tasks:

  - name: stop splunk
    command: ${splunk_cmd_sh1} stop removes=${splunk_cmd}
    ignore_errors: true

  - name: delete splunk_home_sh1
    file: path=${splunk_home_sh1} state=absent

  - name: get splunk pkg
    get_url: dest=/tmp/splunk.tgz force=yes url=${splunk_pkg_url}

  - name: extract splunk pkg
    command: tar xzf /tmp/splunk.tgz chdir=${splunk_home_sh1_parent} creates=${splunk_cmd_sh1}

  - name: chmod 0644 ${server_conf}
    file: path=${server_conf} mode=0644

  - name: enable admin login in ${server_conf}
    lineinfile: dest=${server_conf} regexp='allowRemoteLogin=' line='allowRemoteLogin = always' state=present

  - name: chmod 0644 ${props_conf}
    file: path=${props_conf} mode=0644

  - name: start splunk
    command: ${splunk_cmd_sh1} start --accept-license --answer-yes --auto-ports removes=${splunk_cmd_sh1}
    register: start_splunk_outpuplunk

  - name: set search-server
    shell: ${splunk_cmd_sh1} add search-server ${splunk_server1}:9998 -remoteUsername admin -remotePassword changeme -auth admin:changeme
